#!/usr/bin/env python3
"""danotes
danotes .dan format notes writer


    Most Common Uses:

    # Start a new document from the scratch
    danotes block write file.dan --buid 0 

    # Start a new article
    danotes block write file.dan --label "My New Article"

    Output: 4f 

    # Append some text to the new article
    danotes block write file.dan --buid 4f --input "Here is some text"

    # Append some text to the new article (stdin)
    echo "Here is some other text" | danotes block write file.dan --buid 4f

    # Append a Dan Link to that article
    danotes link write file.dan --buid 4f --label "New Link"

    Output: 1

    # Update the whole Document
    danotes block write file.dan

"""

import argparse

# ./danotes --help
# ./danotes block --help
# ./danotes block write --help
# ./danotes block write --text -b 02

## ----------------------------------------------------------------------------
# @section CLI_HANDLER_FUNCTIONS


def block_write(json, text, buid, label, filename):
    """Write a determined Dan Block Object. 
    If not target Block given write on next <buid>.
    If target Block already exists will append text to it"""
    print(f"Writing {json=} {text=} {buid=} {filename=} {input=} {label=} ")

def block_show(json, text, buid, label, filename):
    """Show and update a determined Dan Block Object
    If no --json and --text are given. Update in place the determined block
    If no --buid or --label are given. Show all the document from buid=0 to last
    """
    print(f"Showing {json=} {text=} {buid=} {label=} {filename=}")


def link_write(json, text, buid, label, filename):
    """Write a determined Dan Link Object"""
    print(f"Writing {json=} {text=} {buid=} {uuid=} {label=} {filename=}")


def link_show(json, text, buid, label, filename):
    """Show and update a determined Dan Link Object"""
    print(f"Showing {json=} {text=} {buid=} {uuid=} {label=} {filename=}")




## EOF EOF EOF CLI_HANDLER_FUNCTIONS 
## ----------------------------------------------------------------------------


## ----------------------------------------------------------------------------
# @section TOP_LEVEL_PARSER

parser = argparse.ArgumentParser(
    prog="danotes",
    description=__doc__,
    formatter_class=argparse.RawDescriptionHelpFormatter
)

subparsers = parser.add_subparsers(dest="command", required=True, help="Top-level command")


## EOF EOF EOF TOP_LEVEL_PARSER 
## ----------------------------------------------------------------------------





## ----------------------------------------------------------------------------
# @section BLOCK

block_parser = subparsers.add_parser("block", help="Dan Block Objects Operations")
block_subparsers = block_parser.add_subparsers(dest="subcommand", required=True)


# block write
block_write_parser = block_subparsers.add_parser("write", help=block_write.__doc__, description=block_write.__doc__)

block_write_parser_outputtype = block_write_parser.add_mutually_exclusive_group()
block_write_parser_outputtype.add_argument("--json", help="Output to stdout as Danom Object", action="store_true", default=False)
block_write_parser_outputtype.add_argument("--text", help="Output to stdout as formated dan text", action="store_true", default=False)

block_write_parser_filterby = block_write_parser.add_mutually_exclusive_group(required=True)
block_write_parser_filterby.add_argument("-b", "--buid", help="Target Block by buid")


block_write_parser.add_argument("-i", "--input", help="Text to Input (If not present defaults to stdin)")
block_write_parser.add_argument("-l", "--label", help="Text Label of the New Block Target (for when creating a new block)")



# block show
block_show_parser = block_subparsers.add_parser("show", help=block_show.__doc__, description=block_show.__doc__)
block_show_parser_outputtype = block_show_parser.add_mutually_exclusive_group()
block_show_parser_outputtype.add_argument("--json", help="Output to stdout as Danom Object", action="store_true", default=False)
block_show_parser_outputtype.add_argument("--text", help="Output to stdout as formated dan text", action="store_true", default=True)

block_show_parser_filterby = block_show_parser.add_mutually_exclusive_group(required=True)
block_show_parser_filterby.add_argument("-b", "--buid", help="Target Block by buid")
block_show_parser_filterby.add_argument("-l", "--label", help="Target Block by label (must be unambiguous)")

block_show_parser.add_argument("filename", help="Input file")

## EOF EOF EOF BLOCK 
## ----------------------------------------------------------------------------




## ----------------------------------------------------------------------------
# @section LINK

link_parser = subparsers.add_parser("link", help="Dan Link Objects Operations")
link_subparsers = link_parser.add_subparsers(dest="subcommand", required=True)


# link write
link_write_parser = link_subparsers.add_parser("write", help=link_write.__doc__, description=link_write.__doc__)

link_write_parser_outputtype = link_write_parser.add_mutually_exclusive_group()
link_write_parser_outputtype.add_argument("--json", help="Output to stdout as Danom Object", action="store_true", default=False)
link_write_parser_outputtype.add_argument("--text", help="Output to stdout as formated dan text", action="store_true", default=False)

link_write_parser_filterby =  link_write_parser.add_mutually_exclusive_group(required=True)
link_write_parser_filterby.add_argument("-b", "--buid", help="Target Block by buid")
link_write_parser_filterby.add_argument("-u", "--uuid", help="[Experimental] Select a determined uuid if it does exist it will substitute the previous link")

link_write_parser.add_argument("filename", help="File to be modified , if not set would output to stdout")


link_write_parser.add_argument("-l", "--label", help="Text Label of the Link (If not present defaults to stdin)")


# link show
link_show_parser = link_subparsers.add_parser("show", help=link_show.__doc__, description=link_show.__doc__)

link_show_parser_outputtype = link_show_parser.add_mutually_exclusive_group()
link_show_parser_outputtype.add_argument("--json", help="Output to stdout as Danom Object", action="store_true", default=False)
link_show_parser_outputtype.add_argument("--text", help="Output to stdout as formated dan text", action="store_true", default=True)

link_show_parser_filterby = link_show_parser.add_mutually_exclusive_group(required=True)
link_show_parser_filterby.add_argument("-b", "--buid", help="Target Link buid")
link_show_parser_filterby.add_argument("-u", "--uuid", help="Target Link uuid")
link_show_parser_filterby.add_argument("-l", "--label", help="[Experimental] Target Link by Block label (must be unambiguous)")


link_show_parser.add_argument("filename", help="Input file")


## EOF EOF EOF LINK 
## ----------------------------------------------------------------------------




## ----------------------------------------------------------------------------
# @section PARSE_AND_DISPATCH

args = parser.parse_args()

if args.command == "block":
    if args.subcommand == "show":
        block_show(args.json, args.text, args.buid, args.label, args.filename)
    elif args.subcommand == "write":
        block_write(args.json, args.text, args.buid, args.label, args.filename)

elif args.command == "link":
    if args.subcommand == "show":
        link_show(args.json, args.text, args.buid, args.label, args.filename)
    elif args.subcommand == "write":
        link_write(args.json, args.text, args.buid, args.label, args.filename)


## EOF EOF EOF PARSE_AND_DISPATCH 
## ----------------------------------------------------------------------------
